import "./globals.css";
import type { Metadata } from "next";

import { Tajawal } from "next/font/google"; 
import Navbar from "@/components/Navbar/Navbar"; 
import Footer from "@/components/Footer/Footer"; 

// Keep the Tajawal font import
const tajawal = Tajawal({ subsets: ["arabic"], weight: ["400", "700"] });


export const metadata: Metadata = {
  title: "Clean Iraq",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en" dir="rtl"> 
      <body className={tajawal.className}>
        <Navbar /> 

        {children}
        <Footer />
      </body>
    </html>
  );
}
