import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "./theme-provider";

import { Tajawal } from "next/font/google";
import Nav from "@/components/Navbar/Nav";
import Footer from "@/components/Footer/Footer";

// Keep the Tajawal font import
const tajawal = Tajawal({ subsets: ["arabic"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Clean Iraq",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" style={{colorScheme:"light"}}>
      <body className={tajawal.className}>
        <ThemeProvider attribute="class" defaultTheme="system" >
        <Nav />

         {children}
        <Footer />
        </ThemeProvider>
       
      </body>
    </html>
  );
}
